-- MySQL Script generated by MySQL Workbench
-- Mon Jul 31 20:47:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tranquil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tranquil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tranquil` DEFAULT CHARACTER SET utf8mb4 ;
USE `tranquil` ;

-- -----------------------------------------------------
-- Table `tranquil`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tranquil`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `role`ENUM('customer', 'staff', 'manager') NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
ALTER TABLE `tranquil`.`user` AUTO_INCREMENT = 1001;



-- -----------------------------------------------------
-- Table `tranquil`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tranquil`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `customer_fname` VARCHAR(45) NULL DEFAULT NULL,
  `customer_lname` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`customer_id`, `user_id`),
  INDEX `fk_customer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_customer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tranquil`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tranquil`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tranquil`.`room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `room_number` INT NULL DEFAULT NULL,
  `room_type` Enum('standard', 'deluxe', 'suite') NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `availability` VARCHAR(10) NULL DEFAULT NULL,
  `price_per_night` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tranquil`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tranquil`.`reservation` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `check_in_date` DATE NULL DEFAULT NULL,
  `check_out_date` DATE NULL DEFAULT NULL,
  `total_room_charge` DECIMAL(10,0) NOT NULL,
  `selected_services` VARCHAR(60) NULL DEFAULT NULL,
  `special_needs` VARCHAR(60) NULL DEFAULT NULL,
  `total_price` DECIMAL(10,0) NOT NULL,
  `comfirmed` BOOLEAN DEFAULT 0,
  `reservation_time` timestamp,
  PRIMARY KEY (`reservation_id`, `customer_id`, `room_id`),
  INDEX `fk_reservation_room1_idx` (`room_id` ASC),
  INDEX `fk_reservation_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_reservation_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `tranquil`.`room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservation_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `tranquil`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
ALTER TABLE `tranquil`.`reservation` AUTO_INCREMENT = 10001;


-- -----------------------------------------------------
-- Table `tranquil`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tranquil`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `reservation_id` INT NOT NULL,
  `amount` DECIMAL(10,0) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  `method` Enum('credit card', 'online payment', 'cash','refund') NULL DEFAULT NULL,
  `payment_status` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`, `reservation_id`),
  INDEX `fk_payment_reservation1_idx` (`reservation_id` ASC),
  CONSTRAINT `fk_payment_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `tranquil`.`reservation` (`reservation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tranquil`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tranquil`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `staff_fname` VARCHAR(45) NULL DEFAULT NULL,
  `staff_lname` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `is_manager` TINYINT NULL DEFAULT NULL,
  `employment_status` Enum('part-time', 'full-time') NULL DEFAULT NULL,
  `main_position` Enum('front-desk', 'maintenance-technician','housekeeper') NULL DEFAULT NULL,
  
  PRIMARY KEY (`staff_id`, `user_id`),
  INDEX `fk_staff_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_staff_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tranquil`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tranquil`.`workschedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tranquil`.`workschedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `staff_id` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `shift` Enum('morning', 'afternoon', 'evening') NULL DEFAULT NULL,
  `status` Enum('completed','cancelled','missed','pending') NULL DEFAULT 'pending',
  PRIMARY KEY (`schedule_id`, `staff_id`),
  INDEX `fk_workschedule_staff1_idx` (`staff_id` ASC),
  CONSTRAINT `fk_workschedule_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `tranquil`.`staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

INSERT INTO `tranquil`.`user` (`password`, `role`) VALUES
('password1', 'staff'),
('password2', 'staff'),
('password3', 'staff'),
('password4', 'staff'),
('password5', 'staff'),
('password6', 'customer'),
('password7', 'customer'),
('password8', 'customer'),
('password9', 'customer'),
('password10', 'customer'),
('password11', 'customer'),
('password12', 'customer'),
('password13', 'customer'),
('password14', 'customer'),
('password15', 'customer');

INSERT INTO `tranquil`.`customer` (`user_id`, `customer_fname`, `customer_lname`, `email`, `phone`) VALUES
(1006, 'Olivia', 'Jones', 'olivia.jones@example.com', '6549873210'),
(1007, 'James', 'Miller', 'james.miller@example.com', '9873216540'),
(1008, 'Sophia', 'Davis', 'sophia.davis@example.com', '1592634870'),
(1009, 'Benjamin', 'Garcia', 'benjamin.garcia@example.com', '7539514862'),
(1010, 'Ava', 'Martinez', 'ava.martinez@example.com', '8642097531'),
(1011, 'Ethan', 'Rodriguez', 'ethan.rodriguez@example.com', '2468135790'),
(1012, 'Mia', 'Lopez', 'mia.lopez@example.com', '1357924680'),
(1013, 'Noah', 'Hernandez', 'noah.hernandez@example.com', '5790246138'),
(1014, 'Isabella', 'Gonzalez', 'isabella.gonzalez@example.com', '8642097531'),
(1015, 'Liam', 'Perez', 'liam.perez@example.com', '7539514862');

INSERT INTO `tranquil`.`staff` (`user_id`, `staff_fname`, `staff_lname`, `email`, `phone`, `is_manager`,`employment_status`,`main_position`) VALUES
(1001, 'John', 'Doe', 'john.doe@example.com', '1234567890', 1,'full-time','front-desk'),
(1002, 'Jane', 'Smith', 'jane.smith@example.com', '9876543210', 1,'full-time','front-desk'),
(1003, 'Michael', 'Johnson', 'michael.johnson@example.com', '4567891230', 0,'full-time','maintenance-technician'),
(1004, 'Emily', 'Williams', 'emily.williams@example.com', '7891234560', 0,'full-time','maintenance-technician'),
(1005, 'William', 'Brown', 'william.brown@example.com', '3216549870', 0,'part-time','housekeeper');

INSERT INTO `tranquil`.`room` (`room_number`, `room_type`, `description`, `availability`, `price_per_night`) VALUES
(101, 'standard', 'Cozy and comfortable standard room', 'available', 300.00),
(102, 'standard', 'Cozy and comfortable standard room', 'available', 300.00),
(103, 'standard', 'Cozy and comfortable standard room', 'available', 300.00),
(104, 'deluxe', 'Spacious and luxurious deluxe room', 'available', 500.00),
(105, 'deluxe', 'Spacious and luxurious deluxe room', 'available', 500.00),
(106, 'suite', 'Luxurious suite with additional amenities', 'available', 800.00);

INSERT INTO `tranquil`.`reservation` (`customer_id`, `room_id`, `check_in_date`, `check_out_date`, `total_room_charge`,`total_price`,`comfirmed`,`reservation_time`) VALUES
(1, 1, '2023-08-01', '2023-08-02', 300.00,300.00,1,'2023-06-15 14:30:00'),
(2, 2, '2023-07-30', '2023-08-01', 600.00,600.00,1,'2023-06-15 14:30:00'),
(3, 3, '2023-08-02', '2023-08-03', 300.00,300.00,1,'2023-06-15 14:30:00'),
(4, 4, '2023-08-02', '2023-08-03', 500.00,500.00,1,'2023-06-15 14:30:00'),
(5, 5, '2023-08-01', '2023-08-02', 500.00,500.00,1,'2023-06-15 14:30:00'),
(6, 6, '2023-08-03', '2023-08-04', 800.00,800.00,1,'2023-06-15 14:30:00'),
(7, 1, '2023-08-04', '2023-08-05', 300.00,300.00,1,'2023-06-15 14:30:00'),
(8, 2, '2023-08-04', '2023-08-06', 600.00,600.00,1,'2023-06-15 14:30:00'),
(1, 3, '2023-08-05', '2023-08-06', 300.00,300.00,1,'2023-06-15 14:30:00'),
(1, 4, '2023-08-05', '2023-08-06', 500.00,500.00,1,'2023-06-15 14:30:00');

INSERT INTO `tranquil`.`payment` (`reservation_id`, `amount`, `date`, `time`, `method`, `payment_status`) VALUES
(10001, 300.00, '2023-08-01', '12:30:00', 'credit card', 'paid'),
(10002, 600.00, '2023-07-30', '10:15:00', 'online payment', 'paid'),
(10003, 300.00, '2023-08-02', '14:00:00', 'credit card', 'paid'),
(10004, 500.00, '2023-08-02', '16:45:00', 'cash', 'paid'),
(10005, 500.00, '2023-08-01', '18:30:00', 'credit card', 'paid'),
(10006, 800.00, '2023-08-03', '11:00:00', 'online payment', 'paid'),
(10007, 300.00, '2023-08-04', '09:45:00', 'credit card', 'pending'),
(10008, 600.00, '2023-08-04', '15:20:00', 'cash', 'pending'),
(10009, 300.00, '2023-08-05', '13:10:00', 'credit card', 'pending'),
(10010, 500.00, '2023-08-05', '17:30:00', 'credit card', 'pending');

INSERT INTO `tranquil`.`workschedule` (`staff_id`, `date`, `shift`,`status`) VALUES
(1, '2023-10-02', 'morning','completed'),
(2, '2023-10-02', 'afternoon','completed'),
(2, '2023-10-02', 'evening','completed'),
(3, '2023-10-03', 'morning','completed'),
(5, '2023-10-03', 'afternoon','completed'),
(1, '2023-10-03', 'evening','completed'),
(3, '2023-10-04', 'morning','completed'),
(4, '2023-10-04', 'afternoon','completed'),
(4, '2023-10-04', 'evening','completed'),
(5, '2023-10-05', 'morning','completed'),
(3, '2023-10-05', 'afternoon','cancelled'),
(2, '2023-10-05', 'evening','completed'),
(1, '2023-10-06', 'morning','completed'),
(4, '2023-10-06', 'afternoon','missed'),
(5, '2023-10-06', 'evening','completed'),
(1, '2023-10-07', 'morning','completed'),
(2, '2023-10-07', 'afternoon','completed'),
(3, '2023-10-07', 'evening','completed'),
(4, '2023-10-08', 'morning','completed'),
(5, '2023-10-08', 'afternoon','completed'),
(2, '2023-10-08', 'evening','completed'),
(3, '2023-10-09', 'morning','pending'),
(5, '2023-10-09', 'afternoon','pending'),
(4, '2023-10-09', 'evening','pending'),
(1, '2023-10-10', 'morning','pending'),
(1, '2023-10-10', 'afternoon','pending'),
(2, '2023-10-10', 'evening','pending'),
(2, '2023-10-11', 'morning','pending'),
(4, '2023-10-11', 'afternoon','pending'),
(5, '2023-10-11', 'evening','pending'),
(3, '2023-10-12', 'morning','pending'),
(2, '2023-10-12', 'afternoon','pending'),
(5, '2023-10-12', 'evening','pending'),
(4, '2023-10-13', 'morning','pending'),
(2, '2023-10-13', 'afternoon','pending'),
(1, '2023-10-13', 'evening','pending'),
(3, '2023-10-14', 'morning','pending'),
(4, '2023-10-14', 'afternoon','pending'),
(5, '2023-10-14', 'evening','pending'),
(5, '2023-10-15', 'morning','pending'),
(1, '2023-10-15', 'afternoon','pending'),
(2, '2023-10-15', 'evening','pending');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

